name: Deployment pipeline

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
  build_lint_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install && cd frontend && npm install
      - name: lint
        run: npm run lint
      - name: npm run build:ui
        run: npm run build:ui
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build:ui
          start: npm start
          wait-on: http://localhost:8080 
      - name: deploying
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm run deploy:full

  simple_deployment_pipeline:
    needs: [build_lint_test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install && cd frontend && npm install
      - name: deploying
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm run deploy:full

